FROM resin/%%RESIN_MACHINE_NAME%%-debian:jessie
WORKDIR /usr/src/app

COPY ./build.sh ./
COPY ./start.sh ./
COPY ./ovpn.sh ./
COPY ./ovpn-stop.sh ./
COPY ./ca.crt ./

RUN ./build.sh

CMD ["/bin/bash"]

